const GAME_CONFIG = {
  WIDTH:  800,
  HEIGHT: 550,
  TIME_PER_ORDER: 15000, 
  MIN_TIME:        7000,
  TIME_BONUS_MAX:  30,
  LIVES_START:     3,
  SCORE_PER_LEVEL: 120,
};

const COLORS = {
  BG_SKY:     0xFFE0B2,
  BG_WALL:    0xFFCC80,
  BG_FLOOR:   0xA1887F,
  COUNTER:    0x6D4C41,
  COUNTER_HI: 0x8D6E63,
  PANEL:      0xFFF8E1,
  PANEL_BORDER:0xFFD54F,
  HEADER:     0xFF6B35,
  HEADER_2:   0xFF8E53,
  TEXT_DARK:  0x3E2723,
  TEXT_LIGHT: 0xFFF8E1,
  SUCCESS:    0x4CAF50,
  DANGER:     0xF44336,
  WARNING:    0xFF9800,
  TIMER_OK:   0x4CAF50,
  TIMER_WARN: 0xFF9800,
  TIMER_BAD:  0xF44336,
};

const INGREDIENTS = [
  { id: 'rice',    icon: '🍚', name: 'Nasi',    col: 0 },
  { id: 'egg',     icon: '🥚', name: 'Telur',   col: 1 },
  { id: 'onion',   icon: '🧅', name: 'Bawang',  col: 2 },
  { id: 'chili',   icon: '🌶️', name: 'Cabai',   col: 3 },
  { id: 'soy',     icon: '🫙', name: 'Kecap',   col: 4 },
  { id: 'chicken', icon: '🍗', name: 'Ayam',    col: 5 },
  { id: 'tofu',    icon: '🧊', name: 'Tahu',    col: 6 },
  { id: 'shrimp',  icon: '🍤', name: 'Udang',   col: 7 },
];

const RECIPES = [
  {
    name:  'Nasi Goreng',
    emoji: '🍳',
    needs: ['rice', 'egg', 'onion', 'soy'],
    pts:   30,
    level: 1,
    tip:   'Klasik warung!',
  },
  {
    name:  'Nasi Ayam',
    emoji: '🍱',
    needs: ['rice', 'chicken', 'onion'],
    pts:   25,
    level: 1,
    tip:   'Simpel tapi enak!',
  },
  {
    name:  'Tahu Telur',
    emoji: '🍽️',
    needs: ['tofu', 'egg', 'onion'],
    pts:   20,
    level: 1,
    tip:   'Murah meriah!',
  },
  {
    name:  'Ayam Bakar',
    emoji: '🔥',
    needs: ['chicken', 'onion', 'chili', 'soy'],
    pts:   40,
    level: 2,
    tip:   'Wangi banget!',
  },
  {
    name:  'Tumis Tahu',
    emoji: '🥘',
    needs: ['tofu', 'onion', 'chili', 'soy'],
    pts:   30,
    level: 2,
    tip:   'Pedas segar!',
  },
  {
    name:  'Udang Saus',
    emoji: '🦐',
    needs: ['shrimp', 'chili', 'onion', 'soy'],
    pts:   45,
    level: 2,
    tip:   'Mewah banget!',
  },
  {
    name:  'Goreng Campur',
    emoji: '🥗',
    needs: ['rice', 'egg', 'chicken', 'chili'],
    pts:   50,
    level: 3,
    tip:   'Komplit!',
  },
  {
    name:  'Nasi Udang Pedas',
    emoji: '🌶️',
    needs: ['rice', 'shrimp', 'chili', 'onion', 'soy'],
    pts:   60,
    level: 3,
    tip:   'Mantap jiwa!',
  },
];
